dependencies {
    implementation project(":core-domain")
    implementation project(":db-core")

    //spring - web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('bootJar') {
    enabled = true
}

tasks.named('jar') {
    enabled = false
}