services:
  content-db:
    image: postgis/postgis:16-3.4
    container_name: content-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: content
      POSTGRES_USER: content
      POSTGRES_PASSWORD: content!@
      TZ: Asia/Ho_Chi_Minh
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - content-network
#  TODO: Redis, etc.

networks:
  content-network:
    driver: bridge

volumes:
  postgres_data:
